export const navigation = [
  { path: "/stopwatch", name: "stopwatch" },
  { path: "/clickoutside", name: "clickoutside" },
  { path: "/perform-action", name: "perform action" },
  { path: "/multistepform", name: "multistep form" },
  { path: "/jira-clone", name: "jira clone" },
  { path: "/infinite-scrolling", name: "infinite scrolling" },
  { path: "/admin-sidebar-toggle", name: "admin sidebar toggle" },
  { path: "/custom-memo", name: "custom memo" },
  { path: "/fixed-footer", name: "fixed footer animation" },
  { path: "/debounce", name: "debounce" },
  { path: "/autocomplete", name: "autocomplete" },
  { path: "/cursor-move", name: "cursor move" },
  { path: "/otp", name: "otp" },
  { path: "/progress-bar", name: "progress bar" },
  { path: "/holy-grail-layout", name: "holy grail layout" },
  { path: "/tabs", name: "tabs(compound pattern)" },
  { path: "/toast", name: "toast" },
  { path: "/pagination", name: "pagination" },
  { path: "/custom-switch", name: "custom switch" },
  { path: "/spinner", name: "spinner" },
  { path: "/typehead-autosuggestion", name: "typehead autosuggestion" },
];
